### ISSUE TITLE
Backwards compatibility with local memcached

### ISSUE THREAD

**Issue by tinio** [gusdan/django-elasticache#10]
Hi,
  Is django-elasticache not supposed to be backwards compatible with memcached (i.e. using 127.0.0.1:11211 for local development)? 

It's not a big deal, as I can change based on DEBUG.
Just curious if this was as intended.

Thanks.

**Comment by gusdan** [comment]
Good question, but I don't think we should support backwards compatibility.

**Comment by trienism** [comment]
Hi, I also ran into this issue and I think it should be backwards compatible as it results in a more complex development workflow. For example, when I'm running integration tests I now need to either use a different caching backend (which is really not testing the "live" environment) or I need to spin up an ElastiCache endpoint. 

I don't think it would be terribly difficult to add backwards support?
