### ISSUE TITLE
Thread-safe?

### ISSUE THREAD

**Issue by petrklus** [gusdan/django-elasticache#11]
I am just trying the plugin and I am getting the following in my logs:

https://gist.github.com/petrklus/5413792e24d87885e05033ab8e0e7d09

Seems that it may be a threading issue with the libmemcached - is there any further configuration needed to get your module fully set up?

**Comment by gusdan** [comment]
Do you have some special instalation? I tested it in different combinations including gevent and eventlet, but i cannot reproduce your error.

**Comment by petrklus** [comment]
It's running on ElasticBeanstalk, pretty standard multi-threaded setup I would say

**Comment by gusdan** [comment]
Did you try to use just vanilla PyLibMemcache?

**Comment by gusdan** [comment]
@petrklus Did you have chance to check it?

**Comment by petrklus** [comment]
@gusdan no, moved away to a different hosting setup
