### ISSUE TITLE
WrongProtocolVersion for memcached package on Ubuntu 14.04 (Trusty)

### ISSUE THREAD

**Issue by zbmott** [gusdan/django-elasticache#13]
`django-elasticache` raises a `WrongProtocolData` exception when using it against a `memcached` backend installed via `apt-get install memcached` on an Ubuntu 14.04 system. This error occurs because the `memcached` server returns "`VERSION 1.4.14 (Ubuntu)`" as the version string, and this runs afoul of the guard in line 35 of `cluster_utils.py`.

**Comment by gusdan** [comment]
You can find your changes in 1.0.0 version. Thank you for help.
