### ISSUE TITLE
Can't Clear Cache

### ISSUE THREAD

**Issue by selected-pixel-jameson** [gusdan/django-elasticache#29]
I'm trying to clear the cache using the Django core cache via```cache.clear()``` and it doesn't appear to be working. This works when I'm testing locally. Does this library not support clearing the cache?

**Comment by gusdan** [comment]
It supposed to work and it works on our clusters. Could you check it deeply from console? like
```
cache.set(1, 1, 100000)
cache.clear()
cache.get(1)
```

**Comment by selected-pixel-jameson** [comment]
Sorry. This was my fault. Wasn't setting things up correctly.
