### ISSUE TITLE
release version 0.0.3 to pypi

### ISSUE THREAD

**Issue by jschneier** [gusdan/django-elasticache#7]
Hey I'd like to use version 0.0.3 and the README on PyPi seems to reflect that I can but when I do:
``pip install django-elasticache==0.0.3`` it fails. However, installing version 0.0.2 works, can you publish the newest one to PyPi?

**Comment by gusdan** [comment]
Oops, sorry. uploaded.

**Comment by jschneier** [comment]
Working! Thanks for the quick response!
